### ISSUE TITLE
Package index doesn't gets updated

### ISSUE THREAD

**Issue by jmslbam** [wp-cli/package-index#33]
Although `packages.json` gets modified when I run the scripts locally.

I found out when https://github.com/sebastiaandegeus/wp-cli-salts-command had a wrong composer.json and we updated this for so it had the correct urls in it.
https://github.com/sebastiaandegeus/wp-cli-salts-command/commit/1e69f8b60dfe32555654de5ac22b6185b7a6b9d9
https://github.com/sebastiaandegeus/wp-cli-salts-command/commit/8d38ed5d936ee2b7099fc6966bef0a6127dd45df

Then even after that the package index doens't gets updated. It should be, because `git ls-files -m` should see that it has been changed with the correct homepage url's etc.

I now hope that because I added [a new repo to the .txt](https://github.com/wp-cli/package-index/commit/4f4a5b286b172094c0694f82c1b5d89f2e33a1e4) file the cron picks it update and Satis parsed it correct and the package index gets updated

**Comment by frozzare** [comment]
@danielbachhuber I noticed that the [package-index](http://wp-cli.org/package-index/) hasn't been updated since `2014-11-10T18:01:44-0500` so new repositories in `repositories.txt` aren't in [package-index](http://wp-cli.org/package-index/). Any fix for this?

**Comment by danielbachhuber** [comment]
> I noticed that the package-index hasn't been updated since 2014-11-10T18:01:44-0500 so new repositories in repositories.txt aren't in package-index. Any fix for this?

We've disabled the Package Index indefinitely. See https://github.com/wp-cli/wp-cli/issues/1564
