### ISSUE TITLE
Trouble adding this as a source of repositories to composer 

### ISSUE THREAD

**Issue by stewarty** [wp-cli/package-index#36]
Hi there,

When trying to add as a source of repositories to composer.json either manually or via the command line instructions (https://github.com/wp-cli/wp-cli/wiki/Community-Packages) results in the following error.

` [Composer\Downloader\TransportException]                                                                                        
  The "http://wp-cli.org/package-index/include/all$cc60c5b828017a7c5627c4edfd8afe1a341d368c.json" file could not be downloaded (HTTP/1.1 404 Not Found) `

Looks like there is no package.json or similar that composer is looking for.

**Comment by danielbachhuber** [comment]
Our Package Index is down while we sort out how we want to support them going forward. Sorry for any inconvenience: https://github.com/wp-cli/wp-cli/issues/1564
